/* generated by unplugin-react-components */
export {}
declare global{
	const App: typeof import('./src/App')['default']
	const Navbar: typeof import('./src/components/Navbar')['default']
	const Contact: typeof import('./src/components/pages/Contact')['default']
	const Diaporama: typeof import('./src/components/pages/Diaporama')['default']
	const Heatmap: typeof import('./src/components/pages/Heatmap')['default']
	const WhoAmI: typeof import('./src/components/pages/WhoAmI')['default']
	const Button: typeof import('./src/components/utils/Button')['default']
}